/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/gen-api-types.mjs.
 * Do not edit by hand. Run `npm run gen:api` to refresh.
 */

export type paths = {
    "/ai-insight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * AI Market Oracle verdict
         * @description RSI, ATR, sentiment, fair-value anchor and a short LLM-written
         *     consensus for a single ticker. Budgeted at **10 rpm per user**.
         */
        get: operations["getAIInsight"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/briefing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily AI briefing
         * @description The most recent AI-written market roll-up plus per-symbol verdicts
         *     for the session's most active tickers.
         */
        get: operations["getBriefing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Batch OHLC for up to four symbols
         * @description Four-way compare in a single round-trip. Drives the Terminal's
         *     normalised overlay chart.
         */
        get: operations["getCompare"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch OHLC history
         * @description OHLC bars for a single symbol. Intervals sample the underlying
         *     tick stream into candles server-side.
         */
        get: operations["getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market-news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Market-wide news feed
         * @description Market-wide headlines (no ticker scope). Uses the same scoring pipeline as `/news`.
         */
        get: operations["getMarketNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market-sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Turnover-weighted sector rollup
         * @description Average % change, total volume, breadth counts, and top-gainer / worst-loser per sector.
         */
        get: operations["getMarketSectors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest market snapshot
         * @description One row per listed symbol with last price, % change, and session volume.
         */
        get: operations["getMarketSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Caller identity
         * @description Username, role, email + verification state, linked OAuth provider, password state.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List watchlist alert rules
         * @description All rules belonging to the caller — armed and paused. A rule fires at most once before going to paused.
         */
        get: operations["listAlertRules"];
        put?: never;
        /**
         * Create a watchlist alert
         * @description Requires a verified email on the caller's account. Returns `403`
         *     if the email is unverified even for Pro callers.
         */
        post: operations["createAlertRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/alerts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Rule ID. */
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an alert rule */
        delete: operations["deleteAlertRule"];
        options?: never;
        head?: never;
        /**
         * Update an alert rule
         * @description Partial update — any subset of `threshold`, `op`, `metric`, `enabled` may be present.
         */
        patch: operations["updateAlertRule"];
        trace?: never;
    };
    "/me/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List your API keys
         * @description Only the prefix is stored server-side. The raw key is returned only at creation time.
         */
        get: operations["listAPIKeys"];
        put?: never;
        /**
         * Provision a new API key
         * @description The raw `key` field is returned **once**. Store it at the callsite — it cannot be recovered later.
         */
        post: operations["createAPIKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke an API key
         * @description Subsequent requests presenting this key return `401`.
         */
        delete: operations["revokeAPIKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ticker news feed
         * @description Recent headlines for a ticker, each scored with a recency-weighted
         *     sentiment value in `[-1, +1]`.
         */
        get: operations["getTickerNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Natural-language screen
         * @description Plain-text questions resolved against a whitelisted SQL surface.
         *     Budgeted at **10 rpm per user**.
         */
        post: operations["naturalQuery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All listed symbols
         * @description Every ticker listed on the exchange. Updated as the collector ingests the daily feed.
         */
        get: operations["getSymbols"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Caller's watchlist
         * @description Starred symbols with the latest market snapshot joined on.
         */
        get: operations["getWatchlist"];
        put?: never;
        /**
         * Add or remove a symbol from the watchlist
         * @description Idempotent toggle — posting the same symbol twice returns it to its previous state.
         */
        post: operations["toggleWatchlist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        AIInsight: {
            /** @example true */
            aboveSMA20?: boolean;
            /** @example true */
            aboveSMA50?: boolean;
            /** @example Constructive setup: price holds above both moving averages… */
            analysis?: string;
            /** @example 0.084 */
            atr?: number;
            /** @example 78 */
            confidence?: number;
            /** @example 1.43 */
            fairValue?: number;
            /** @example 62.4 */
            rsi?: number;
            /** @example 62 */
            sampleSize?: number;
            /** @example 0.71 */
            sentiment?: number;
            /** @example Positive */
            sentimentLabel?: string;
            /**
             * @example BULLISH
             * @enum {string}
             */
            signal: "BULLISH" | "BEARISH" | "NEUTRAL";
            /** @example 1.48 */
            suggestedPrice?: number;
            /** @example MTNGH */
            symbol: string;
        };
        APIKey: {
            /**
             * Format: date-time
             * @example 2026-03-22T10:12:00Z
             */
            createdAt?: string;
            /**
             * Format: int64
             * @example 3
             */
            id: number;
            /**
             * Format: date-time
             * @example 2026-04-14T09:40:00Z
             */
            lastUsedAt?: string | null;
            /** @example my-laptop */
            name?: string;
            /**
             * @description First few characters of the key
             * @example ges_live_aZ8k
             */
            prefix: string;
        };
        APIKeyWithSecret: components["schemas"]["APIKey"] & {
            /**
             * @description The raw secret. Returned **only** from this endpoint, **only** at creation time.
             * @example ges_live_qR4v9n8xK2pLm1dC5wY3zH7vE6tB0sJ4uA8iO
             */
            key: string;
        };
        AlertRule: components["schemas"]["AlertRuleInput"] & {
            /** @example false */
            enabled: boolean;
            /** @example 1 */
            fireCount: number;
            /**
             * Format: int64
             * @example 142
             */
            id: number;
            /**
             * Format: date-time
             * @example 2026-04-14T15:31:02Z
             */
            lastFiredAt?: string | null;
            /**
             * Format: int64
             * @example 9
             */
            userId: number;
        };
        AlertRuleInput: {
            /**
             * @example price
             * @enum {string}
             */
            metric: "price" | "rsi" | "pct_change";
            /**
             * @example >
             * @enum {string}
             */
            op: ">" | "<" | ">=" | "<=";
            /** @example MTNGH */
            symbol: string;
            /** @example 1.5 */
            threshold: number;
        };
        Briefing: {
            /** @example 0.31 */
            averageSentiment?: number;
            insights?: {
                rsi?: number;
                sentiment?: number;
                symbol?: string;
                /** @enum {string} */
                verdict?: "Constructive" | "Neutral" | "Cautious";
            }[];
            /** @example Financials extended a three-session advance as MTNGH tagged a fresh YTD high… */
            summary: string;
            /**
             * Format: date
             * @example 2026-04-14
             */
            tradingDate: string;
        };
        Error: {
            /** @description Human-readable error message. */
            error: string;
        };
        MarketSnapshot: {
            /** @example 1.54 */
            lastPrice: number;
            /** @example 1.5 */
            openPrice?: number;
            /** @example 2.67 */
            percentChange?: number;
            /** @example 0.04 */
            priceChange?: number;
            /** @example MTNGH */
            symbol: string;
            /**
             * Format: int64
             * @example 211800
             */
            volume?: number;
        };
        MeResponse: {
            availableProviders?: {
                /** @example Google */
                displayName?: string;
                /** @example google */
                name?: string;
            }[];
            /**
             * Format: email
             * @example trader@example.com
             */
            email?: string;
            /** @example true */
            emailVerified?: boolean;
            /** @example true */
            hasPassword?: boolean;
            /** @example false */
            isAdmin?: boolean;
            isAuthenticated: boolean;
            /** @example google */
            provider?: string;
            /**
             * Format: email
             * @example trader@example.com
             */
            providerEmail?: string;
            /**
             * @example pro
             * @enum {string}
             */
            role?: "basic" | "pro" | "admin";
            /** @example accra_trader */
            username?: string;
        };
        NewsItem: {
            /**
             * Format: date-time
             * @example 2026-04-14T08:12:00Z
             */
            publishedAt?: string;
            /**
             * @description Recency-weighted score in `[-1, +1]`.
             * @example 0.62
             */
            sentiment?: number;
            /** @example Business Day GH */
            source?: string;
            /** @example MTN Ghana posts Q1 subscriber gains, lifts data revenue 18% */
            title: string;
        };
        OHLCBar: {
            /** @example 1.54 */
            close: number;
            /** @example 1.55 */
            high?: number;
            /** @example 1.5 */
            low?: number;
            /** @example 1.5 */
            open?: number;
            /**
             * Format: date-time
             * @example 2026-04-14T15:30:00Z
             */
            timestamp: string;
            /**
             * Format: int64
             * @example 211800
             */
            volume?: number;
        };
        QueryResponse: {
            /**
             * @example [
             *       "symbol",
             *       "rsi",
             *       "ytd_return",
             *       "last_price"
             *     ]
             */
            columns?: string[];
            /** @description The whitelisted SQL the LLM resolved to. */
            generatedSQL?: string;
            /** @description Echo of the submitted question. */
            question?: string;
            /**
             * @description Row-major result set. Each element is an array aligned with `columns`.
             * @example [
             *       [
             *         "GCB",
             *         31.2,
             *         4.7,
             *         6.92
             *       ],
             *       [
             *         "SCB",
             *         28.9,
             *         1.3,
             *         21.25
             *       ]
             *     ]
             */
            rows: unknown[][];
        };
        SectorMover: {
            /** @example 2.18 */
            percentChange?: number;
            /** @example GCB */
            symbol?: string;
        };
        SectorRollup: {
            /** @example 6 */
            advanceCount?: number;
            /** @example 1.14 */
            avgPctChange?: number;
            /** @description Omitted when the `detail=summary` query flag is set. */
            constituents?: components["schemas"]["MarketSnapshot"][];
            /** @example 2 */
            declineCount?: number;
            /** @example 1 */
            neutralCount?: number;
            /** @example Financials */
            sector: string;
            topGainer?: components["schemas"]["SectorMover"];
            /** @example 2814500 */
            totalTurnover?: number;
            /**
             * Format: int64
             * @example 412600
             */
            totalVolume?: number;
            worstLoser?: components["schemas"]["SectorMover"];
        };
        WatchlistResponse: {
            details?: components["schemas"]["MarketSnapshot"][];
            /**
             * @example [
             *       "MTNGH",
             *       "GCB",
             *       "FML"
             *     ]
             */
            symbols: string[];
        };
    };
    responses: {
        /** @description Missing or malformed parameter. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "symbol is required"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rule limit exceeded, duplicate, or conflicting state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "alert rule limit exceeded"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated but not Pro/Admin on a Pro-only endpoint, or no verified email for alerts. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "pro access required"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such resource, or not owned by the caller. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "not found"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Per-IP or per-user rate budget exhausted. Back off exponentially. */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "rate limit exceeded"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid bearer token / session cookie. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "unauthorized"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    getAIInsight: {
        parameters: {
            query: {
                /** @description Ticker. */
                symbol: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Oracle verdict envelope. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIInsight"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    getBriefing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Briefing envelope with per-symbol insights. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Briefing"];
                };
            };
        };
    };
    getCompare: {
        parameters: {
            query: {
                /** @description Comma-separated tickers, max four. */
                symbols: string;
                /** @description Defaults to `1d`. */
                interval?: "1d" | "1w" | "1M";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Map of symbol → OHLC series. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["OHLCBar"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getHistory: {
        parameters: {
            query: {
                /** @description Ticker (e.g. `MTNGH`). */
                symbol: string;
                /** @description Sampling window. */
                interval: "1d" | "1w" | "1M";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of OHLC bars, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OHLCBar"][];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
        };
    };
    getMarketNews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of scored headlines. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsItem"][];
                };
            };
        };
    };
    getMarketSectors: {
        parameters: {
            query?: {
                /** @description Pass `summary` to drop the `constituents` array (~70% smaller payload). */
                detail?: "summary" | "full";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of sector rollups. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorRollup"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getMarketSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of per-symbol snapshots. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketSnapshot"][];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Identity envelope. Fields beyond `isAuthenticated` are present only for signed-in callers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    listAlertRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of alert rules. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleInput"];
            };
        };
        responses: {
            /** @description The new rule's ID. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int64
                         * @example 143
                         */
                        id: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Rule ID. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Rule ID. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    enabled?: boolean;
                    /** @enum {string} */
                    metric?: "price" | "rsi" | "pct_change";
                    /** @enum {string} */
                    op?: ">" | "<" | ">=" | "<=";
                    /** @example 1.6 */
                    threshold?: number;
                };
            };
        };
        responses: {
            /** @description Updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAPIKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of API keys (no raw secret). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKey"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description Display label, max 200 characters.
                     * @example screener-bot
                     */
                    name?: string;
                };
            };
        };
        responses: {
            /** @description The new key — including the raw secret. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKeyWithSecret"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Key ID. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revocation confirmation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example revoked */
                        status?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getTickerNews: {
        parameters: {
            query: {
                /** @description Ticker to fetch headlines for. */
                symbol: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of scored headlines. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsItem"][];
                };
            };
        };
    };
    naturalQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Plain-English query. Max 16 KiB.
                     * @example Banks with RSI below 35 and positive YTD return
                     */
                    question: string;
                };
            };
        };
        responses: {
            /** @description Resolved rows with the generated SQL for audit. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    getSymbols: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of ticker symbols. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    getWatchlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Watchlist envelope. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    toggleWatchlist: {
        parameters: {
            query: {
                /** @description Ticker to toggle. */
                symbol: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New membership state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        isWatchlisted: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
