apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gse-terminal
resources:
- namespace.yaml
- storageclass.yaml
- secrets.yaml
- serviceaccount.yaml
- postgres.yaml
- questdb.yaml
- redis.yaml
- app.yaml
- app-spot.yaml
- ingress.yaml
- networkpolicy.yaml
- vpa.yaml
